# Generated by Django 2.0.4 on 2018-07-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180716_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
