# Generated by Django 2.0.4 on 2018-07-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_barcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(default='', max_length=155),
        ),
    ]
