# Generated by Django 2.0.4 on 2018-07-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180716_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='piece_number',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
