# Generated by Django 2.0.4 on 2018-07-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180716_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('bill_number', models.CharField(max_length=155)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.RenameModel(
            old_name='Withdrawals',
            new_name='Withdrawal',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='item',
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
    ]
