# Generated by Django 2.0.4 on 2018-07-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180716_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='piece_number',
            field=models.CharField(max_length=155, unique=True, verbose_name='Número de Pieza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
