# Generated by Django 2.0.4 on 2018-07-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180717_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='employee',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
