# Generated by Django 2.0.4 on 2018-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='', max_length=155, verbose_name='Unidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='piece_number',
            field=models.CharField(max_length=155, unique=True, verbose_name='Número de Parte'),
        ),
    ]
