# Generated by Django 2.0.4 on 2018-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180720_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.TextField(choices=[('gasolina', 'Gasolina'), ('producto_terminado', 'Producto Terminado'), ('accesorios', 'Accesorios'), ('refacciones', 'Refacciones')], default='gasolina', verbose_name='Área'),
            preserve_default=False,
        ),
    ]
