# Generated by Django 2.0.4 on 2018-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_item_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='Código de barras'),
        ),
    ]
