# Generated by Django 2.0.4 on 2018-09-07 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20180723_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=155, verbose_name='SKU')),
                ('name', models.CharField(max_length=155, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=155, verbose_name='Marca')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('part_number', models.CharField(max_length=155, verbose_name='Número de Parte')),
                ('measuring_unit', models.TextField(verbose_name='Unidad de Medida')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='area',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='piece_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='appraisal',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Costo Estimado'),
        ),
        migrations.AddField(
            model_name='item',
            name='individual_details',
            field=models.TextField(blank=True, verbose_name='Detalles Individuales'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.SKU'),
            preserve_default=False,
        ),
    ]
