# Generated by Django 2.0.4 on 2018-09-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20180907_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='0', max_length=255, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sku',
            name='measuring_unit',
            field=models.CharField(max_length=155, verbose_name='Unidad de Medida'),
        ),
    ]
