# Generated by Django 2.0.4 on 2018-09-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180917_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
