# Generated by Django 2.0.4 on 2018-09-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Alto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Largo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ancho'),
            preserve_default=False,
        ),
    ]
