# Generated by Django 2.0.4 on 2018-09-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20180918_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='modelo',
            new_name='model',
        ),
    ]
